import turtle as t
import math
t.title("Mathematical functions ")
t.bgcolor("black")
print("functions available :\n\ny = x\ny = |x|\ny = [x]\ny = x^2\ny = sin\ny = cos")
a=input("\nEnter a function y = ")
if a=='x':
    def graph():
        t.color("white")
        t.speed(5)
        t.left(90)
        t.penup()
        t.forward(250)
        t.pendown()
        t.backward(500)
        t.forward(250)
        t.left(90)
        t.penup()
        t.forward(300)
        t.pendown()
        t.backward(600)
        t.forward(300)

        t.right(90)
    graph()
    def st():
        t.shape("turtle")
        t.pensize(3)
        t.color("blue")
        t.right(45)
        t.penup()
        t.backward(250)
        t.pendown()
        t.speed(1)
        t.forward(250)
        t.forward(250)
        t.speed(3)
        t.backward(250)
    st()
    def eqn():
        t.penup()
        t.goto(60,150)
        t.color("white")
        t.write("f(x) = x",font=("calibri",15,"bold"))
        t.color("white")
        t.pensize(1)
        t.shape("triangle")
        t.shapesize(0.3)
        t.left(30)
        t.goto(0,0)
    eqn()
elif a=="|x|":
    def graph():
        t.color("white")
        t.speed(5)
        t.left(90)
        t.penup()
        t.forward(250)
        t.pendown()
        t.backward(500)
        t.forward(250)
        t.left(90)
        t.penup()
        t.forward(300)
        t.pendown()
        t.backward(600)
        t.forward(300)
        t.right(90)
    graph()
    def v():
        t.left(45)
        t.penup()
        t.forward(200)
        t.pendown()
        t.speed(1)
        t.pensize(4)
        t.color("blue")
        t.shape("turtle")
        t.backward(200)
        t.right(90)
        t.forward(200)
        t.shape("triangle")
        t.shapesize(0.3)
        t.backward(200)
        t.color("black")
        t.left(45)
        t.speed(4)
    v()
    def eqn():
        t.penup()
        t.forward(100)
        t.right(90)
        t.forward(20)
        t.right(90)
        t.color("white")
        t.write("y = |x|",font=("calibri",15,"bold"))
        t.left(90)
        t.color("black")
        t.backward(20)
        t.left(90)
        t.backward(100)
    eqn()
elif a=="[x]":
    def graph():
        t.color("white")
        t.speed(5)
        t.left(90)
        t.penup()
        t.forward(250)
        t.pendown()
        t.backward(500)
        t.forward(250)
        t.left(90)
        t.penup()
        t.forward(300)
        t.pendown()
        t.backward(600)
        t.forward(300)
        t.right(90)
    graph()
    def step():
        t.right(90)
        t.shape("turtle")
        t.color("blue")
        t.width(4)
        t.speed(1)
        x=0
        while x<5:
            t.forward(50)
            t.penup()
            t.left(90)
            t.forward(30)
            t.right(90)
            t.pendown()
            x+=1
        t.shape("triangle")
        t.speed(4)
        t.shapesize(0.4)
        t.color("black")
        t.right(180)
        t.penup()
        t.left(90)
        t.forward(20)
        t.right(90)
        t.forward(160)
        t.pendown()
        t.color("white")
        t.write("y = [x]",font=("calibri",15,"bold"))
        t.color("black")
        t.left(58)
        t.penup()
        t.forward(150)
        t.right(45)
        t.forward(10)
        t.right(90) 
    step()
elif a=="x^2":
    def graph():
        t.color("white")
        t.speed(5)
        t.up()
        t.left(90)
        t.fd(250)
        t.down()
        t.backward(500)
        t.up()
        t.fd(50)
        t.left(90)
        t.fd(250)
        t.down()
        t.backward(500)
        t.fd(250)
        t.right(90)
    graph()
    def curve():
        t.color("blue")
        t.shape("turtle")
        t.pensize(4)
        def draw(minX,maxX,step,func):
            originalSpeed = t.speed()
            t.speed(0)
            t.up()
            t.goto(minX , func(minX))
            t.speed(originalSpeed)
            t.down()
            for x in range(minX,maxX+step, step):
                t.goto(x,func(x))
        def poly(a,b,c):
            def func(x):
                return a*x*x + b*x + c
            return func
        draw(-200,200,1,poly(0.01,0,-200))
        t.up()
        t.goto(30,100)
        t.color("white")
        t.write("y = x^2",font=("calibri",15,"bold"))
        t.shape("triangle")
        t.shapesize(0.3)
        t.goto(0,-200)
    curve()
elif a=="sin":
    def graph():
        t.color("white")
        t.speed(5)
        t.left(90)
        t.penup()
        t.forward(250)
        t.pendown()
        t.backward(500)
        t.forward(250)
        t.left(90)
        t.penup()
        t.forward(300)
        t.pendown()
        t.backward(600)
        t.forward(300)
        t.right(90)
        t.speed(3)
    graph()
    def sin():
        t.shape("turtle")
        t.pensize(3)
        t.color("blue")
        t.left(180)
        t.penup()
        t.goto(-300,70)
        t.pendown()
        for i in range(-300,300):
            x=math.sin(math.radians(i))
            t.goto(i,x*80)
    sin()
    def word():
        t.penup()
        t.goto(80,150)
        t.shape("triangle")
        t.shapesize(0.3)
        t.pensize(5)
        t.color("white")
        t.write("y=sin",font=("calibri",15,"bold"))
        t.goto(0,0)
        t.color("white")
    word()
elif a=="cos":
    def graph():
        t.color("white")
        t.speed(5)
        t.left(90)
        t.penup()
        t.forward(250)
        t.pendown()
        t.backward(500)
        t.forward(250)
        t.left(90)
        t.penup()
        t.forward(300)
        t.pendown()
        t.backward(600)
        t.forward(300)
        t.right(90)
        t.speed(3)
    graph()
    def cos():
        t.shape("turtle")
        t.pensize(3)
        t.color("blue")
        t.left(180)
        t.penup()
        t.goto(-300,40)
        t.pendown()
        for i in range(-300,300):
            x=math.cos(math.radians(i))
            t.goto(i,x*80)
    cos()
    def word():
        t.penup()
        t.goto(80,150)
        t.shape("triangle")
        t.shapesize(0.3)
        t.pensize(5)
        t.color("white")
        t.write("y=cos",font=("calibri",15,"bold"))
        t.goto(0,0)
        t.color("white")
    word()
